"""empty message

Revision ID: 0a6714113d73
Revises: bc4b43fd4dd7
Create Date: 2019-02-12 09:54:31.425201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6714113d73'
down_revision = 'bc4b43fd4dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('attempted_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('attempted_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('attempted_physics', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('negative_score_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('negative_score_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('negative_score_physics', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('positive_score_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('positive_score_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('positive_score_physics', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('total_score_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('total_score_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('total_score_physics', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('un_attempted_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('un_attempted_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('un_attempted_physics', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_test', 'un_attempted_physics')
    op.drop_column('user_test', 'un_attempted_maths')
    op.drop_column('user_test', 'un_attempted_chemistry')
    op.drop_column('user_test', 'total_score_physics')
    op.drop_column('user_test', 'total_score_maths')
    op.drop_column('user_test', 'total_score_chemistry')
    op.drop_column('user_test', 'positive_score_physics')
    op.drop_column('user_test', 'positive_score_maths')
    op.drop_column('user_test', 'positive_score_chemistry')
    op.drop_column('user_test', 'negative_score_physics')
    op.drop_column('user_test', 'negative_score_maths')
    op.drop_column('user_test', 'negative_score_chemistry')
    op.drop_column('user_test', 'attempted_physics')
    op.drop_column('user_test', 'attempted_maths')
    op.drop_column('user_test', 'attempted_chemistry')
    # ### end Alembic commands ###
