"""empty message

Revision ID: 0d8b3d7337a8
Revises: 334ad7a96f81
Create Date: 2019-02-25 08:29:38.295839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d8b3d7337a8'
down_revision = '334ad7a96f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('solution', sa.String(length=1000), nullable=True))
    op.alter_column('question', 'question_content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=3000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=3000),
               nullable=True)
    op.drop_column('question', 'solution')
    # ### end Alembic commands ###
