"""empty message

Revision ID: 0dc32ff5346c
Revises: c03a2041b0b1
Create Date: 2019-02-19 04:57:39.447177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc32ff5346c'
down_revision = 'c03a2041b0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('e', sa.String(length=500), nullable=True))
    op.add_column('user_test', sa.Column('time_taken', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_test', 'time_taken')
    op.drop_column('question', 'e')
    # ### end Alembic commands ###
