"""empty message

Revision ID: 334ad7a96f81
Revises: 0dc32ff5346c
Create Date: 2019-02-25 08:28:24.523532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '334ad7a96f81'
down_revision = '0dc32ff5346c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=3000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=3000),
               nullable=False)
    # ### end Alembic commands ###
