"""empty message

Revision ID: 3dda379d7e3b
Revises: 9a1a0d365cdb
Create Date: 2019-01-30 10:22:11.935185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dda379d7e3b'
down_revision = '9a1a0d365cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], )
    )
    op.create_table('user_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.Column('positive_score', sa.Integer(), nullable=False),
    sa.Column('negative_score', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('no_answers', sa.Integer(), nullable=False),
    sa.Column('attempted_ques', sa.Integer(), nullable=False),
    sa.Column('test_taken_on_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'user_id')
    )
    op.drop_table('user_tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tests',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('test_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('positive_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('negative_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('correct_answers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('wrong_answers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('no_answers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('attempted_ques', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('test_taken_on_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name='user_tests_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_tests_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_test')
    op.drop_table('tags')
    op.drop_table('parent')
    op.drop_table('child')
    # ### end Alembic commands ###
