"""empty message

Revision ID: 3ea2f38ab4cc
Revises: 98c1b93fb4c2
Create Date: 2019-01-29 08:55:39.148647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea2f38ab4cc'
down_revision = '98c1b93fb4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['parent_id', 'child_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    # ### end Alembic commands ###
