"""empty message

Revision ID: 5295afd68841
Revises: 8bfe347a9e5b
Create Date: 2019-01-30 22:02:22.795294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5295afd68841'
down_revision = '8bfe347a9e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child')
    op.drop_table('parent')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('child_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], name='tags_ibfk_1'),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], name='tags_ibfk_2'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('parent',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('parent_name', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('child',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('child_name', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
