"""empty message

Revision ID: 75407c9d5eaa
Revises: 6ecd086fa4e8
Create Date: 2019-02-09 09:53:36.636305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75407c9d5eaa'
down_revision = '6ecd086fa4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_user_test_timestamp'), 'user_test', ['timestamp'], unique=False)
    op.drop_column('user_test', 'test_taken_on_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('test_taken_on_date', mysql.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_user_test_timestamp'), table_name='user_test')
    op.drop_column('user_test', 'timestamp')
    # ### end Alembic commands ###
