"""empty message

Revision ID: 7778b9c7cf7a
Revises: 0a6714113d73
Create Date: 2019-02-12 10:57:52.694885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7778b9c7cf7a'
down_revision = '0a6714113d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('marks_chemistry', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('marks_maths', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('marks_physics', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'marks_physics')
    op.drop_column('test', 'marks_maths')
    op.drop_column('test', 'marks_chemistry')
    # ### end Alembic commands ###
