"""empty message

Revision ID: 8bfe347a9e5b
Revises: 3dda379d7e3b
Create Date: 2019-01-30 21:45:47.469917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe347a9e5b'
down_revision = '3dda379d7e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('correct_answers', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('wrong_answers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'wrong_answers')
    op.drop_column('tags', 'correct_answers')
    # ### end Alembic commands ###
