"""empty message

Revision ID: 9ae62602d991
Revises: 9d6c2531ae25
Create Date: 2019-02-12 23:15:06.620096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae62602d991'
down_revision = '9d6c2531ae25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question_image')
    # ### end Alembic commands ###
