"""empty message

Revision ID: 9d6c2531ae25
Revises: d329e33e84ba
Create Date: 2019-02-12 22:59:13.427580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6c2531ae25'
down_revision = 'd329e33e84ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('sub_section', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'sub_section')
    op.drop_column('question', 'level')
    # ### end Alembic commands ###
