"""empty message

Revision ID: bc4b43fd4dd7
Revises: 582e6fd0f3a0
Create Date: 2019-02-10 02:02:26.762677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4b43fd4dd7'
down_revision = '582e6fd0f3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_confirmed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_confirmed')
    # ### end Alembic commands ###
