"""empty message

Revision ID: cf3970452b29
Revises: e19554f16c27
Create Date: 2019-02-08 22:40:44.335971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf3970452b29'
down_revision = 'e19554f16c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               nullable=True)
    # ### end Alembic commands ###
