"""empty message

Revision ID: d329e33e84ba
Revises: f20d4a034a64
Create Date: 2019-02-12 11:34:36.139797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd329e33e84ba'
down_revision = 'f20d4a034a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('correct_attempted_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('correct_attempted_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('correct_attempted_physics', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('wrong_attempted_chemistry', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('wrong_attempted_maths', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('wrong_attempted_physics', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_test', 'wrong_attempted_physics')
    op.drop_column('user_test', 'wrong_attempted_maths')
    op.drop_column('user_test', 'wrong_attempted_chemistry')
    op.drop_column('user_test', 'correct_attempted_physics')
    op.drop_column('user_test', 'correct_attempted_maths')
    op.drop_column('user_test', 'correct_attempted_chemistry')
    # ### end Alembic commands ###
