"""empty message

Revision ID: f20d4a034a64
Revises: 7778b9c7cf7a
Create Date: 2019-02-12 11:05:11.668290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f20d4a034a64'
down_revision = '7778b9c7cf7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('author_chemistry', sa.String(length=120), nullable=True))
    op.add_column('test', sa.Column('author_maths', sa.String(length=120), nullable=True))
    op.add_column('test', sa.Column('author_physics', sa.String(length=120), nullable=True))
    op.add_column('test', sa.Column('no_of_questions_chemistry', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('no_of_questions_maths', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('no_of_questions_physics', sa.Integer(), nullable=False))
    op.add_column('test', sa.Column('total_no_of_questions', sa.Integer(), nullable=False))
    op.drop_column('test', 'no_of_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('no_of_questions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('test', 'total_no_of_questions')
    op.drop_column('test', 'no_of_questions_physics')
    op.drop_column('test', 'no_of_questions_maths')
    op.drop_column('test', 'no_of_questions_chemistry')
    op.drop_column('test', 'author_physics')
    op.drop_column('test', 'author_maths')
    op.drop_column('test', 'author_chemistry')
    # ### end Alembic commands ###
